# Generated by Django 5.2.17 on 2026-09-23 00:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleets", "0001_initial"),
        ("radios", "0002_battery_batteryassignment_maintenanceevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "compatibility_notes",
                    models.TextField(
                        blank=True, help_text="e.g. radio models/firmware this family is meant for"
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="fleets.fleet",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("version_number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=150)),
                ("release_notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="configurations.configuration",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration_versions",
                        to="fleets.fleet",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ChannelSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("zone", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "mode",
                    models.CharField(
                        choices=[("analog", "Analog"), ("digital", "Digital (DMR)")], max_length=10
                    ),
                ),
                (
                    "rx_frequency",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
                ),
                (
                    "tx_frequency",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
                ),
                (
                    "rx_tone",
                    models.CharField(blank=True, help_text="CTCSS/DCS, if used", max_length=20),
                ),
                ("tx_tone", models.CharField(blank=True, max_length=20)),
                ("color_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "timeslot",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "1"), (2, "2")], null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_snapshots",
                        to="fleets.fleet",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="configurations.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("programmed_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_records",
                        to="fleets.fleet",
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_records",
                        to="radios.radio",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programming_records_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programming_records",
                        to="configurations.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-programmed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VersionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_attachments",
                        to="fleets.fleet",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_attachments_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="configurations.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="configuration",
            constraint=models.UniqueConstraint(
                fields=("fleet", "name"), name="unique_configuration_name_per_fleet"
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationversion",
            constraint=models.UniqueConstraint(
                fields=("configuration", "version_number"),
                name="unique_version_number_per_configuration",
            ),
        ),
        migrations.AddConstraint(
            model_name="channelsnapshot",
            constraint=models.UniqueConstraint(
                fields=("version", "position"), name="unique_channel_position_per_version"
            ),
        ),
        migrations.AddIndex(
            model_name="programmingrecord",
            index=models.Index(fields=["fleet", "radio"], name="configurati_fleet_i_8e8309_idx"),
        ),
    ]
