# Generated by Django 5.2.17 on 2026-09-22 23:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("asset_label", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial", models.CharField(blank=True, max_length=100)),
                ("radio_id", models.CharField(blank=True, max_length=100)),
                ("band", models.CharField(blank=True, max_length=50)),
                ("firmware", models.CharField(blank=True, max_length=50)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spotter", "Spotter"),
                            ("crew", "Crew"),
                            ("race_control", "Race control"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("spare", "Spare"),
                            ("repair", "In repair"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radios",
                        to="fleets.fleet",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_label"],
                "indexes": [
                    models.Index(fields=["fleet", "status"], name="radios_radi_fleet_i_9b495a_idx"),
                    models.Index(
                        fields=["fleet", "asset_label"], name="radios_radi_fleet_i_08da89_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fleet", "asset_label"), name="unique_radio_asset_label_per_fleet"
                    )
                ],
            },
        ),
    ]
