# Generated by Django 5.2.17 on 2026-09-23 00:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0001_initial"),
        ("radios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Battery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("asset_label", models.CharField(max_length=100)),
                ("maker", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial", models.CharField(blank=True, max_length=100)),
                ("chemistry", models.CharField(blank=True, max_length=50)),
                (
                    "capacity",
                    models.CharField(blank=True, help_text="e.g. 2200 mAh", max_length=50),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("replace", "Needs replacement"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batteries",
                        to="fleets.fleet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batteries",
                "ordering": ["asset_label"],
            },
        ),
        migrations.CreateModel(
            name="BatteryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battery_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "battery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="radios.battery",
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_assignments",
                        to="fleets.fleet",
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battery_assignments",
                        to="radios.radio",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("inspection", "Inspection"),
                            ("firmware", "Firmware update"),
                            ("antenna", "Antenna"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateField(default=django.utils.timezone.localdate)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_events",
                        to="fleets.fleet",
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_events",
                        to="radios.radio",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_events_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="battery",
            index=models.Index(
                fields=["fleet", "condition"], name="radios_batt_fleet_i_766851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="battery",
            index=models.Index(
                fields=["fleet", "asset_label"], name="radios_batt_fleet_i_d36c43_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="battery",
            constraint=models.UniqueConstraint(
                fields=("fleet", "asset_label"), name="unique_battery_asset_label_per_fleet"
            ),
        ),
        migrations.AddIndex(
            model_name="batteryassignment",
            index=models.Index(fields=["fleet"], name="radios_batt_fleet_i_a258a6_idx"),
        ),
        migrations.AddConstraint(
            model_name="batteryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("battery",),
                name="unique_active_assignment_per_battery",
            ),
        ),
        migrations.AddConstraint(
            model_name="batteryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("radio",),
                name="unique_active_assignment_per_radio",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceevent",
            index=models.Index(fields=["fleet", "radio"], name="radios_main_fleet_i_751225_idx"),
        ),
    ]
